services:
  db:
    image: postgres
    restart: always
    container_name: pharmacy-store
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - default
